import { Router } from "express";
import { db } from "@workspace/db";
import { reportsTable, signsTable, measurementsTable } from "@workspace/db";
import { eq, desc } from "drizzle-orm";
import { randomUUID } from "crypto";

const router = Router();

router.get("/reports", async (req, res) => {
  try {
    const reports = await db.select().from(reportsTable).orderBy(desc(reportsTable.created_at));
    res.json({ reports, total: reports.length });
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

router.post("/reports", async (req, res) => {
  try {
    const body = req.body;
    const id = randomUUID();

    // Compute compliance stats if route_id provided
    let total_signs = 0;
    let compliance_rate = 0;
    let critical_findings = 0;
    let route_name: string | undefined;

    if (body.route_id) {
      const { routesTable } = await import("@workspace/db");
      const [route] = await db.select().from(routesTable).where(eq(routesTable.id, body.route_id)).limit(1);
      route_name = route?.name;
      const signs = await db.select().from(signsTable).where(eq(signsTable.route_id, body.route_id));
      total_signs = signs.length;
      const compliant = signs.filter(s => s.status === "compliant").length;
      critical_findings = signs.filter(s => s.status === "critical").length;
      compliance_rate = total_signs > 0 ? (compliant / total_signs) * 100 : 0;
    }

    const [report] = await db.insert(reportsTable).values({
      id,
      title: body.title,
      route_id: body.route_id,
      route_name,
      type: body.type,
      status: "ready",
      period_start: body.period_start ? new Date(body.period_start) : undefined,
      period_end: body.period_end ? new Date(body.period_end) : undefined,
      total_signs,
      compliance_rate: parseFloat(compliance_rate.toFixed(1)),
      critical_findings,
      generated_by: body.generated_by,
    }).returning();

    res.status(201).json(report);
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

router.get("/reports/:id", async (req, res) => {
  try {
    const [report] = await db.select().from(reportsTable).where(eq(reportsTable.id, req.params.id)).limit(1);
    if (!report) return res.status(404).json({ error: "Not found" });
    res.json(report);
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

router.get("/reports/:id/download", async (req, res) => {
  try {
    const [report] = await db.select().from(reportsTable).where(eq(reportsTable.id, req.params.id)).limit(1);
    if (!report) return res.status(404).json({ error: "Not found" });

    // Gather signs for this report's route (or all signs if no route)
    const { routesTable } = await import("@workspace/db");
    const signs = report.route_id
      ? await db.select().from(signsTable).where(eq(signsTable.route_id, report.route_id))
      : await db.select().from(signsTable);

    // Gather recent measurements for these sign IDs
    const signIds = signs.map(s => s.id);
    let measurements: any[] = [];
    if (signIds.length > 0) {
      const { inArray } = await import("drizzle-orm");
      measurements = await db
        .select()
        .from(measurementsTable)
        .where(inArray(measurementsTable.sign_id, signIds))
        .orderBy(desc(measurementsTable.created_at));
    }

    // Build CSV
    const lines: string[] = [];

    // Report header block
    lines.push(`"NHAI RetroVision — ${report.type.toUpperCase()} REPORT"`);
    lines.push(`"Title","${report.title}"`);
    lines.push(`"Status","${report.status}"`);
    lines.push(`"Route","${report.route_name ?? "All Routes"}"`);
    if (report.period_start && report.period_end) {
      lines.push(`"Period","${new Date(report.period_start).toDateString()} to ${new Date(report.period_end).toDateString()}"`);
    }
    lines.push(`"Generated","${new Date(report.created_at).toISOString()}"`);
    lines.push(`"Generated By","${report.generated_by ?? "System"}"`);
    lines.push(`"Total Assets","${report.total_signs ?? signs.length}"`);
    lines.push(`"Compliance Rate","${report.compliance_rate ?? "—"}%"`);
    lines.push(`"Critical Findings","${report.critical_findings ?? "—"}"`);
    lines.push("");

    // Asset inventory section
    lines.push("ASSET INVENTORY");
    lines.push(["Asset ID","Name","Type","Chainage","Route","Status","Last Reflectivity (mcd/lx/m²)","IRC Threshold","Installed"].join(","));
    for (const s of signs) {
      lines.push([
        s.id,
        `"${s.name}"`,
        s.sign_type,
        s.chainage ?? "",
        `"${s.route_name ?? ""}"`,
        s.status,
        s.last_reflectivity_value ?? "",
        s.irc_threshold ?? "",
        s.installed_date ? new Date(s.installed_date).toDateString() : "",
      ].join(","));
    }
    lines.push("");

    // Measurement log section
    lines.push("MEASUREMENT LOG");
    lines.push(["Measurement ID","Sign Name","Value (mcd/lx/m²)","Method","Condition","Weather","Temperature (°C)","Operator","Measured At"].join(","));
    for (const m of measurements) {
      const sign = signs.find(s => s.id === m.sign_id);
      lines.push([
        m.id,
        `"${sign?.name ?? m.sign_id}"`,
        m.value,
        m.method ?? "",
        m.condition ?? "",
        m.weather ?? "",
        m.temperature ?? "",
        `"${m.operator ?? m.recorded_by ?? ""}"`,
        new Date(m.created_at).toISOString(),
      ].join(","));
    }

    const csv = lines.join("\n");
    const filename = `RetroVision_${report.title.replace(/[^a-z0-9]/gi, "_")}.csv`;

    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.send(csv);
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

router.delete("/reports/:id", async (req, res) => {
  try {
    await db.delete(reportsTable).where(eq(reportsTable.id, req.params.id));
    res.status(204).send();
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
